/* 第1回 SQLで連番を扱う　（4）連番の生成 */
/* 第10回　結合大全　（1）クロス結合で同じテーブルを利用する */
DROP TABLE Digits;

CREATE TABLE Digits(digit INTEGER PRIMARY KEY);

INSERT INTO Digits VALUES(0);
INSERT INTO Digits VALUES(1);
INSERT INTO Digits VALUES(2);
INSERT INTO Digits VALUES(3);
INSERT INTO Digits VALUES(4);
INSERT INTO Digits VALUES(5);
INSERT INTO Digits VALUES(6);
INSERT INTO Digits VALUES(7);
INSERT INTO Digits VALUES(8);
INSERT INTO Digits VALUES(9);